#!/bin/sh

# Load up GHCi with an appropriate environment
#
DISTDIR=$(stack path --dist-dir)
stack exec ghci -- \
  -j +RTS -N -A64M -n2m -RTS \
  -package ghc \
  -iaccelerate-llvm/${DISTDIR}/build/autogen \
  -iaccelerate-llvm-native/${DISTDIR}/build \
  -iaccelerate-llvm-native/${DISTDIR}/build/autogen \
  -iaccelerate-llvm-ptx/${DISTDIR}/build/autogen \
  $@

